from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
import uuid
from django.urls import reverse
from django.contrib import messages
from .paystack import checkout
from projectsApp.models import Project
from .models import DonationHistory
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import hmac
import hashlib
from django.conf import settings
import json
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from decimal import Decimal, InvalidOperation
# Create your views here.
def donation(request, donation_id):

    project = Project.objects.get(id=donation_id)

    context = {
        'project': project,
    }

    return render(request, 'paymentsApp/donation_checkout.html', context)


@login_required
def payment_successful(request, project_id):

    project = Project.objects.get(id=project_id)
    print(f"User: {request.user}, Project: {project}")
    
    # Get the most recent successful donation for this user and project
    donation = DonationHistory.objects.filter(
        user=request.user,
        project=project,
        donation_status=True
    ).order_by('-date').first()
    
    amount = donation.amount if donation else None

    return render(request, 'paymentsApp/payment_success.html', {
        'project': project,
        'amount': amount
    })

@login_required
def payment_failed(request, project_id):

    project = Project.objects.get(id=project_id)
    
    # Get the most recent failed donation for this user and project (optional)
    donation = DonationHistory.objects.filter(
        user=request.user,
        project=project,
        donation_status=False
    ).order_by('-date').first()
    
    amount = donation.amount if donation else None
    
    return render(request, 'paymentsApp/payment_failed.html', {
        'project': project,
        'amount': amount
    })

@login_required
def create_paystack_checkout_session(request, project_id):
    project = Project.objects.get(id=project_id)

    if request.method == "POST":
        amount_text = request.POST.get("amount")
        try:
            amount = Decimal(amount_text)
        except (InvalidOperation, TypeError):
            messages.error(request, "Enter a valid numeric amount.")
            return redirect('donation', donation_id=project_id)

        # validate min/max
        if amount <= 0:
            messages.error(request, "Amount must be greater than zero.")
            return redirect('donation', donation_id=project_id)
        
        purchase_id = f"purchase_{uuid.uuid4()}"
        # /payment-success/2/
        payment_success_url = reverse('payment-success', kwargs={'project_id': project_id})
        # http://domain.com/payment-success/2/ 
        callback_url = f"{request.scheme}://{request.get_host()}{payment_success_url}"
        # Paystack expects amount in kobo (or cents) as integer
        amount_in_kobo = int(amount * 100)

        checkout_data = {
        "email": request.user.email,
        "amount": amount_in_kobo,  # in kobo 
        "currency": "KES",
        "channels": ["card", "bank_transfer", "bank", "ussd", "qr", "mobile_money"],
        "reference": purchase_id, # generated by developer
        "callback_url": callback_url,
        "metadata": {
            "product_id": project.id,
            "user_id": request.user.id,
            "purchase_id": purchase_id,
        },
        "label": f"Checkout For {project.name}"
        }
        print("The checkout data payload sent to paystack is as follows:")
        print(checkout_data)
        print("End of paystack checkout data sent")

        status, check_out_session_url_or_error_message = checkout(checkout_data)

        if status:
            return redirect(check_out_session_url_or_error_message)
        else:
            messages.error(request, check_out_session_url_or_error_message)
            return redirect('donation')
    # GET: render form to enter amount
    return render(request, 'paymentsApp/donation_checkout.html', {'project': project})

@csrf_exempt
def paystack_webhook(request):
    secret = settings.PAYSTACK_SECRET_KEY
    request_body = request.body
    
    print("Webhook (raw request_body) from Paystack")
    print(request_body)
    print("End of raw request_body from Paystack")

    hash = hmac.new(secret.encode('utf-8'), request_body, hashlib.sha512).hexdigest()
    
    if hash == request.META.get('HTTP_X_PAYSTACK_SIGNATURE'):
        webhook_post_data = json.loads(request_body)
        print("Webhook data after conversion to json")
        print(webhook_post_data)
        print("End of webhook data after conversion to json")

        if webhook_post_data["event"] == "charge.success":
            metadata = webhook_post_data["data"]["metadata"]
            data = webhook_post_data["data"]
            product_id = metadata["product_id"]
            user_id = metadata["user_id"]
            purchase_id = metadata["purchase_id"]

            amount_paid_kobo = data.get("amount")
            amount_paid = Decimal(amount_paid_kobo) / 100

            user = User.objects.get(id=user_id)

            DonationHistory.objects.create(
                donation_id = purchase_id,
                user = user,
                donation_status = True,
                project = Project.objects.get(id=product_id),
                amount = amount_paid
            )

            #send email to user on successful payment
            # send_payment_success_email(user.email, product_id)

    return HttpResponse(status=200)