from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
import uuid
from django.urls import reverse
from django.contrib import messages
from .paystack import checkout
from projectsApp.models import Project

# Create your views here.
def donation(request, donation_id):

    project = Project.objects.get(id=donation_id)

    context = {
        'project': project,
    }

    return render(request, 'paymentsApp/donation_checkout.html', context)

@login_required
def payment_successful(request, project_id):

    project = Project.objects.get(id=project_id)

    return render(request, 'paymentsApp/payment_success.html', {'project': project})

@login_required
def payment_failed(request, project_id):

    project = Project.objects.get(id=project_id)
    return render(request, 'paymentsApp/payment_failed.html', {'project': project})

@login_required
def create_paystack_checkout_session(request, project_id):
    project = Project.objects.get(id=project_id)
    purchase_id = f"purchase_{uuid.uuid4()}"

    # /payment-success/2/
    payment_success_url = reverse('payment-success', kwargs={'project_id': project_id})
    # http://domain.com/payment-success/2/ 
    callback_url = f"{request.scheme}://{request.get_host()}{payment_success_url}"

    checkout_data = {
       "email": request.user.email,
       "amount": (project.donation) * 100,  # in kobo (₦2500)
       "currency": "KES",
       "channels": ["card", "bank_transfer", "bank", "ussd", "qr", "mobile_money"],
       "reference": purchase_id, # generated by developer
       "callback_url": callback_url,
       "metadata": {
           "product_id": project.id,
           "user_id": request.user.id,
           "purchase_id": purchase_id,
       },
       "label": f"Checkout For {project.name}"
   }
    
    status, check_out_session_url_or_error_message = checkout(checkout_data)

    if status:
        return redirect(check_out_session_url_or_error_message)
    else:
        messages.error(request, check_out_session_url_or_error_message)
        return redirect('donation')
