# Generated by Django 5.2.8 on 2025-11-16 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectsApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="donation",
        ),
    ]
