# Generated by Django 5.2.8 on 2025-12-25 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectsApp", "0002_remove_project_donation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
    ]
