# Generated by Django 5.2.8 on 2025-11-14 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentsApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("71936c7d-7fb9-461b-8d70-ca0ab71b2c1a"),
                max_length=225,
            ),
        ),
    ]
