# Generated by Django 5.2.8 on 2025-11-14 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentsApp", "0002_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("b3eb4308-9dd1-4a37-9b26-58987c2400bc"),
                max_length=225,
            ),
        ),
    ]
