# Generated by Django 5.2.8 on 2025-11-14 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentsApp", "0003_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("d9d08fc4-2792-45bf-a0ec-8539c352df47"),
                max_length=225,
            ),
        ),
    ]
