# Generated by Django 5.2.8 on 2025-11-15 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentsApp", "0004_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("2853f590-09b8-45a1-b69c-6917c2e7f1d1"),
                max_length=225,
            ),
        ),
    ]
