# Generated by Django 5.2.8 on 2025-11-16 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentsApp", "0005_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationhistory",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("84afae01-013f-457b-839f-79b5dffd1922"),
                max_length=225,
            ),
        ),
    ]
