# Generated by Django 5.2.8 on 2025-12-25 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentsApp", "0006_donationhistory_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("695dc70c-f14b-47df-9ad8-401f951f6bcc"),
                max_length=225,
            ),
        ),
    ]
