# Generated by Django 5.2.8 on 2025-12-25 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentsApp", "0007_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationhistory",
            name="user",
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="email",
            field=models.EmailField(default="noemail@example.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("b9a2e712-7682-4ccb-b61a-646e9ddd0731"),
                max_length=225,
            ),
        ),
    ]
