# Generated by Django 5.2.8 on 2025-12-26 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "paymentsApp",
            "0008_remove_donationhistory_user_donationhistory_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="donationhistory",
            name="first_name",
            field=models.CharField(
                blank=True, default="Anonymous", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="last_name",
            field=models.CharField(
                blank=True, default="User", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("1614a4f2-d5f2-47b6-9fca-8e5fbdf6f5d4"),
                max_length=225,
            ),
        ),
    ]
